CREATE TABLE PROJECTS (ID INTEGER PRIMARY KEY, TITLE TEXT , FUNDING_GOAL INTEGER , CATEGORY TEXT , START_DATE TEXT,
  END_DATE TEXT
 );

 CREATE TABLE USERS (ID INTEGER PRIMARY KEY,NAME TEXT, AGE INTEGER);

CREATE TABLE PLEDGES (ID INTEGER PRIMARY KEY, AMOUNT INTEGER, USER_ID INTEGER , PROJECT_ID INTEGER);
